pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'customgive'

new groovy.json.JsonSlurper().parse(file('versions.json')).each { module, target ->
    include(module)
    project(":${module}").projectDir = file("versions/${target.minecraft}")
}
